### PR TITLE
Add inline task editing

### PR DESCRIPTION
**Pull request by LogVoid**
This pull request introduces inline task editing functionality and enhances the task addition process within the To-do App. The following changes have been made:

    Inline Task Editing:
        Users can now edit tasks directly within the task list using an inline editing mode.
        Task edits are saved when the user presses the "Enter" key.
        This improves user experience by allowing modifications without navigating away from the list view.

    Task Addition in Add Bar:
        Tasks can now be added directly using the "Enter" key in the task addition bar.
        This provides a quicker and more intuitive method for adding new tasks without requiring additional clicks.

The code adheres to the project's established style and does not alter its overall formatting or conventions.
 
 Please review the inline editing and task addition enhancements and provide feedback.
 Let me know if there are any additional scenarios or edge cases that should be tested.

Thank you for reviewing this pull request!

### CODE REVIEW

**Comment by chouaib-629** [comment]
Hey there! 👋 Thanks a lot for your commit! 🙏 

I noticed that the Tailwind classes aren't working properly because the project wasn't initialized with Tailwind. Could you please use simple CSS for this project instead? 🚀

Thanks again for your awesome contributions! 💡✨

**Comment by chouaib-629** [comment]
I noticed a couple of things:

Could you please fix the length of the input field?
When clicking on the edit button, the edit and delete buttons should be replaced with check and cancel buttons.

**Comment by LogVoid** [comment]
> Hey there! 👋 Thanks a lot for your commit! 🙏
> 
> I noticed that the Tailwind classes aren't working properly because the project wasn't initialized with Tailwind. Could you please use simple CSS for this project instead? 🚀
> 
> Thanks again for your awesome contributions! 💡✨

I am not sure what you mean by this. the README documentation instructs to initialize Tailwind. Could you please elaborate?

**Comment by LogVoid** [comment]
I just looked at the project again and yes it seems like the Tailwind classes aren't being applied properly. I'm pretty new to web development, so i don't really understand why its not working. I'm going to migrate some of the tailwind to ordinary CSS soon.

**Comment by chouaib-629** [comment]
Oops, my bad! 😅 In the getting started guide, I mentioned installing Tailwind, but it wasn't actually configured or used in the project. Sorry for the mix-up! 🙏

**Pull request merged**
